pull_request_rules:
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=no-mergify
  - author=puiterwijk
  - status-success=CodeFactor
  - status-success=DCO
  - status-success=continuous-integration/travis-ci/pr
  name: default
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - status-success=CodeFactor
  - status-success=DCO
  - status-success=continuous-integration/travis-ci/pr
  name: default
