language: go
# We modify /etc/hosts
sudo: true
git:
  # We need the full repo for the metatest
  depth: false
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - master
env: []
matrix:
  fast_finish: true
  include:
    - env: EXTRATAGS=stress
    - env: FULLUPDATE=yes
  allow_failures:
    - env: EXTRATAGS=stress
    - env: FULLUPDATE=yes
    - go: master
go_import_path: repospanner.org/repospanner
# In no way would I suggest doing curl | sh normally.... But it's not my environment
install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
before_script:
- echo "127.0.0.1   node1.regiona.repospanner.local node2.regiona.repospanner.local node3.regiona.repospanner.local" | sudo tee -a /etc/hosts
script:
- dep ensure
- [ "$FULLUPDATE" == "yes" ] && dep ensure -update
- ./build.sh -tags prof
- go vet ./...
- go test ./... -tags ${EXTRATAGS:-plain} -timeout 9m
cache:
  directories:
  - vendor
