language: go
sudo: false
git:
  # We need the full repo for the metatest
  depth: false
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - master
env: []
matrix:
  fast_finish: true
  include:
    - env: EXTRATAGS=stress
    - env: FULLUPDATE=yes
  allow_failures:
    - env: EXTRATAGS=stress
    - env: FULLUPDATE=yes
    - go: master
go_import_path: repospanner.org/repospanner
# In no way would I suggest doing curl | sh normally.... But it's not my environment
install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
script:
- dep ensure
- ./build.sh -tags prof
- go vet ./...
- go test ./... -tags ${EXTRATAGS:-plain} -timeout 9m
cache:
  directories:
  - vendor
